### ISSUE TITLE
Why Isn't Compose Importable?

### ISSUE THREAD

**Issue by machineghost** [neoziro/recompact#101]
The first example on your front page is:

    import recompact from 'recompact'
    import { pure, withProps } from 'recompact'

    const enhance = recompact.compose(

To a library outsider (especially one coming from recompose where `compose` is just another import) that looks weird: why isn't it simply:

    import { compose, pure, withProps } from 'recompact'

    const enhance = compose(

?

At the very least ES6 syntax allows for combining those two lines into one:

    import recompact, { pure, withProps } from 'recompact'

But since these are literally the first lines of code a newcomer to your library will see, it might be be nice if you could just add a one-line comment or something to explain why such a functionally-focused library requires `compose` to be imported/used as a method rather than as a stand-alone function.

**Comment by ipanasenko** [comment]
This is just an example for `babel-plugin-lodash` optimization

**Comment by machineghost** [comment]
Right, but why have bad public-facing code of any sort?

**Comment by matthieuprat** [comment]
I agree that this is not ideal.

How about

```js
import { recompact, pure, withProps } from 'recompact'
```

Do you want to submit a PR for that?

**Comment by gregberge** [comment]
This library is no longer actively maintained. It will not be solved.
