### ISSUE TITLE
Is 3.3.0 released?

### ISSUE THREAD

**Issue by ipanasenko** [neoziro/recompact#104]
Hey guys. I see v3.3.0 was created a couple days ago, but I got v3.2.1 from npm. Can someone have a look why is this so?

Specifically, I expected `withStateHandlers` to be available, as I try to replace `recompose` with `recompact`

**Comment by neoziro** [comment]
Yes it is!

**Comment by ipanasenko** [comment]
Okay, that's weird, because I see `3.2.1` on https://www.npmjs.com/package/recompact, and `npm view recompact` shows `3.2.1` as latest version.

I will wait a couple days, maybe something is cached somewhere
