### ISSUE TITLE
Advertise Recompose test compatibility and version equivalence

### ISSUE THREAD

**Issue by acjay** [neoziro/recompact#105]
I'm very excited about this library, but two things make me hesitant to integrate:

- I don't know _exactly_ how compatible Recompact is with Recompose. Demonstrating that Recompact passes Recompose's test suite would go a long way toward providing me that reassurance. (Modulo any tests that would be expected to faill, due to intentional observable differences, of course.)
- I also don't know what version of Recompose Recompact is compatible with. That would also be very helpful to know. Recompose appears to be changing slowly, so maybe it's not a huge deal, but still.

Lastly, is there any intention to merge the projects, given their overlap?

**Comment by neoziro** [comment]
This library was very useful, but today you have [React Hooks](https://reactjs.org/docs/hooks-intro.html). Since hooks combine the power of render props and HOC, I think recompact is no longer useful today.
