### ISSUE TITLE
Missing exports

### ISSUE THREAD

**Issue by BenRichter** [neoziro/recompact#109]
After switching from recompose, my IDE PhpStorm signals that it can't find the imported functions/modules. Autocomplete doesn't work either. 
The build work tough, so it seems to be just a usability problem.
![phpstorm](https://user-images.githubusercontent.com/3908676/41277324-2c1bf80e-6e27-11e8-8b4f-1aba4ac95aad.png)

**Comment by neoziro** [comment]
I don't know what is the origin of this problem, anyway PR are welcome to fix it!

**Comment by gregberge** [comment]
This library is no longer actively maintained. It will not be solved.
