### ISSUE TITLE
toRenderProps & fromRenderProps

### ISSUE THREAD

**Issue by vadzim-revolist** [neoziro/recompact#111]
Function toRenderProps & fromRenderProps from recompose are not implemented in recompact.
Are there any plans to implement them?

**Comment by neoziro** [comment]
No, this project is no longer actively maintained. So there is no plan to add these functions into recompact. Composition of HOC is no longer required with hooks, I suggest you to use [React hooks](https://reactjs.org/docs/hooks-intro.html) instead of recompact.

**Comment by brabeji** [comment]
> No, this project is no longer actively maintained. So there is no plan to add these functions into recompact. Composition of HOC is no longer required with hooks, I suggest you to use [React hooks](https://reactjs.org/docs/hooks-intro.html) instead of recompact.

Hello @neoziro ! Please consider adding this info to the top of readme
