### ISSUE TITLE
withState updater doesn't invoke a state changing callback

### ISSUE THREAD

**Issue by deepsweet** [neoziro/recompact#59]
hi.

abstract part of my real code:

```js
compose(
  withState('status', 'setStatus', {}),
  withProps(
    ({ setStatus }) => ({
      go(key) {
        setStatus((prevState) => ({
          ...prevState,
          [key]: true
        }), () => console.log('done!'));
      }
    })
  )
)(Test);
```

no log. but it works fine with HOCs imported from `recompose`.

**Comment by matthieuprat** [comment]
Thank you for raising this issue.

We're expecting to address it this week.

**Comment by matthieuprat** [comment]
In the meantime, you may want to use Recompose's `setState` (Recompose and Recompact are able to work alongside each other).

**Comment by deepsweet** [comment]
yeah, I now, but I'm trying to use `recompact` as a drop-in replacement.

**Comment by deepsweet** [comment]
any news on this?

**Comment by matthieuprat** [comment]
It is actually slightly harder than expected and I am not even sure we can emulate `setState`'s behaviour properly with our implementation. Further more, this will almost certainly have a significant impact on the code base.

Thus, in the end, this might be a feature we won't want to support. If so, we'll update the docs and maybe display a warning in development if a callback is passed to the state updater.

**Comment by matthieuprat** [comment]
One way to work around this would be to use the `componentDidUpdate` lifecycle hook in conjunction with the `lifecycle` HOC.

**Comment by matthieuprat** [comment]
I had a talk with @neoziro and we agreed that for now, it was better to not support the callback argument of the state updater.

Considering the fact that even React itself [recommends](https://facebook.github.io/react/docs/react-component.html#setstate) using `componentDidUpdate()` instead, we feel that this feature is not worth the impact it will have on the code base.

**Comment by mnpenner** [comment]
@matthieuprat 

> Considering the fact that even React itself [recommends](https://facebook.github.io/react/docs/react-component.html#setstate) using `componentDidUpdate()` instead, we feel that this feature is not worth the impact it will have on the code base.

Just curious, where do you see that React "recommends" using `componentDidUpdate` instead?

The current React 16 docs say:

> Instead, use `componentDidUpdate` *or* a **`setState` callback** (`setState(updater, callback)`), either of which are guaranteed to fire after the update has been applied.

**Comment by matthieuprat** [comment]
> The second parameter to `setState()` is an optional callback function that will be executed once `setState` is completed and the component is re-rendered. Generally we recommend using `componentDidUpdate()` for such logic instead.
