### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by prontiol** [neoziro/recompact#64]
Are there any plans to support TypeScript?

**Comment by neoziro** [comment]
Yes we have to support TypeScript, right now it's not the priority. But yes, I am open to PR.

**Comment by neoziro** [comment]
@prontiol what is the requirement to support Typescript? What is missing?

**Comment by prontiol** [comment]
@neoziro TypeScript requires [declaration files](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html).

**Comment by neoziro** [comment]
@prontiol you can copy [recompose types](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/recompose) and add definition for new operators (connectObs, withObs, omitProps, pickProps). Since I have never used TypeScript, it's difficult for me to open a good PR for it.

**Comment by prontiol** [comment]
@neoziro I will try to find some time and make a PR for this.

**Comment by dlindenkreuz** [comment]
Quick fix for the lazy ones:

```ts
// recompact.d.ts
declare module "recompact" {
  export * from "recompose"
}
```

**Comment by pokorson** [comment]
@neoziro TypeScript definition for new package should be added to this repository, correct? 
https://github.com/DefinitelyTyped/DefinitelyTyped/

**Comment by neoziro** [comment]
You have two choices:

- Include package definition in the package itself
- Add package definition to https://github.com/DefinitelyTyped/DefinitelyTyped/

I think adding package definition in the package itself is easier.

**Comment by pokorson** [comment]
@neoziro do you have some work in progress on this or can I try to do it?

**Comment by neoziro** [comment]
No I have never used TypeScript, so I do not know how to do it right. You can try to do it. You can start from "recompose" deifinition it is pretty similar.

**Comment by pokorson** [comment]
yes, that's what I was going to do, thanks!

**Comment by kn0ll** [comment]
from what i have experienced, @types/recompose leads to a not-very-typesafe experience. particularly, it fails to infer chained props correctly from `compose`, making it easy to compose components that end up without the props they need (which should ideally result in compiler error). also there general type weirdness around some of the methods (`withState` comes to mind).

just throwing that out there while someone is trying to tackle the problem... types are not that useful without proper type checking...

**Comment by neoziro** [comment]
It will not happen sorry, this library is no longer actively maintained.
