### ISSUE TITLE
HOCs not being compacted

### ISSUE THREAD

**Issue by MioQuispe** [neoziro/recompact#74]
Hello, I tried substituting recompose with this, and everything works great so far except for the HOCs not being compacted:

![recompact](https://cloud.githubusercontent.com/assets/5080735/25440354/7af5a9d8-2a9f-11e7-99a6-8a4f047baec0.png)

Here's what I'm doing to my component:

```javascript
export default compose(
  setDisplayName('Home'),
  connect(mapStateToProps),
  lifecycle(spec),
  withHandlers(handlers),
)(Home);
```

Everything is imported from recompact and I even removed recompose so it can't be that. Did I miss something? Oh and I'm using the latest version 2.3.2

**Comment by neoziro** [comment]
Hello @MioQuispe, `lifecycle` cannot be recompacted.

You can do a lot of things in `lifecycle`. Compacting it would generate a lot of side effects that's why it's not planed to compact it.

I plan to release some more specific higher-order components that would be compactable. Can you explain what do you do in `spec`?

**Comment by MioQuispe** [comment]
@neoziro 

I wasn't doing anything in it yet, it was left over from something previous that I had moved elsewhere.
So I tried removing the lifecycle and now it looks like this instead:

![recompact2](https://cloud.githubusercontent.com/assets/5080735/25445445/bbac1692-2aae-11e7-8a2a-3cc9c3633036.png)

Is withHandlers also not supported then?

Thanks for answering and for your work on this library!

**Comment by MioQuispe** [comment]
@neoziro 

Using setDisplayName & connect:

![recompact3](https://cloud.githubusercontent.com/assets/5080735/25445866/e13d636a-2aaf-11e7-9d95-8641d3010375.png)

Only using connect:

![recompact4](https://cloud.githubusercontent.com/assets/5080735/25445877/e7583900-2aaf-11e7-8485-3abebb9568ed.png)

**Comment by neoziro** [comment]
@MioQuispe `withHandlers` is supported but `connect` is from redux, so it can't be recompacted.
@MioQuispe with `setDisplayName` you renamed the next component, the next component is `Connect(Home)` and you renamed it in "Home", the second "Home" is your final component.

**Comment by MioQuispe** [comment]
@neoziro I see, everything makes sense now. Could be useful to document this perhaps?

**Comment by neoziro** [comment]
@MioQuispe yes I will improve documentation soon.
