### ISSUE TITLE
withPropsOnChange doesn't execute when the given props are undefined

### ISSUE THREAD

**Issue by mnpenner** [neoziro/recompact#91]
Here's a little code snippet to demonstrate the problem:

```js
import cc from 'classcat';
import {withPropsOnChange} from 'recompact';

export default function className(klass) {
    console.log('helllo',klass);
    return withPropsOnChange(['className'], ({className}) => {
        let tmp = klass || className;
        console.log('TTTTTTTTMPPPPPPPPPPPPP',tmp,klass,className);
        if(tmp) {
            return {
                className: klass && className
                    ? cc([klass,className])
                    : tmp
            }
        }
    });
}
```

When `className` is undefined, `recompose` will print "TTTTTTTTMPPPPPPPPPPPPP" but `recompact` will not.

i.e., `recompact` doesn't execute the function when `shouldMapOrKeys` refers to `undefined` props.

I understand why it may have implemented this way -- normally when using this HOC you're computing a new value from the old value, and if the old value is undefined the new one usually will be too -- but in this case I still want it to run.

----

**Edit:** Actually, I don't know what's going on. It looks like [this](https://github.com/neoziro/recompact/blob/6d3650a764179444a2a40aea4f1bfc266c18afde/src/withPropsOnChange.js#L54) should unconditionally execute, but it doesn't. All I know is the behaviour is different between `recompose` and `recompact`.

**Comment by gregberge** [comment]
This library is no longer actively maintained. It will not be solved.
