### ISSUE TITLE
Flow type support?

### ISSUE THREAD

**Issue by FezVrasta** [neoziro/recompact#94]
Hi, can we simply use the types of Recompose or does this library needs its own set to properly support Flow?

Thanks.

**Comment by neoziro** [comment]
You can use type of recompose or build it for recompact. I don't use Flow, so I can't create types, I need help.

**Comment by neoziro** [comment]
It will not happen sorry, this library is no longer actively maintained.

**Comment by fabienjuif** [comment]
Hi @neoziro , I am curious about all the closed issues, and this message.

Why do you drop the maintenance of recompact ?
Is it because of recompose droping maintenance ?
Is it because of hooks ? 

No pressure, just curious about it :)

**Comment by neoziro** [comment]
Hello, it is because of Hooks, I think hoc composition is no longer a good pattern.
